
DATASTORE_YML: "datastore.yml"

pathes:
    ROOT_PATH: "/mnt/samba/Daten/Projekte/web/"
    DATA: "data/"                 # not used yet
    LOG: "log/"
    RRD: "rrd/"

suffixes:
    log: # "-%Y_%m_%d__%H-%M-%S"     #date and time
         "-%Y_%m_%d"                #date only
         #""                         # hostname only
    data: "-%Y_%m_%d__%H-%M-%S"     #date and time
          #"-%Y_%m_%d"               #date only
          #""                        #without date and time

debug:
    datefmt: "%d.%m.%Y %H:%M:%S"      # normal
    #datefmt: "%d.%m.%Y %H:%M:%S.%s"   # fine (with ms)
    hirestime: True                    # time resolution in data logs (true=ms, false=s)
    logYML: True                      #put the yml-file into the log
    verbose: True

