
DATASTORE_YML: "datastore.yml"

pathes:
    ROOT_PATH: "/mnt/samba/Daten/Projekte/web/"
    DATA: "data/"                 # not used yet
    LOG: "log/"
    RRD: "rrd/"
    YML: "yml/"

suffixes:
    log: # "-%Y_%m_%d__%H-%M-%S"     #date and time
         "-%Y_%m_%d"                #date only
         #""                         # hostname only
    data: "-%Y_%m_%d__%H-%M-%S"     #date and time
          #"-%Y_%m_%d"               #date only
          #""                        #without date and time

debug:
    datefmt: "%d.%m.%Y %H:%M:%S"      # normal
    #datefmt: "%d.%m.%Y %H:%M:%S.%s"   # fine (with ms)
    hirestime: True                    # time resolution in data logs (true=ms, false=s)
    logYML: True                      #put the yml-file into the log
    verbose: True

devices:
    -   No_Name_70_03_9F_9A_7C_05
    -   Schnell_AC_0B_FB_D6_41_74
    -   Langsam_CC_50_E3_3C_17_68

    -   Wohnzimmer_44_17_93_1C_1A_E0
    -   ToF_Sensor_BC_DD_C2_24_3B_F4
    -   Pumpe_CC_50_E3_53_1E_58
    -   Schuppen-DS_44_17_93_1B_FF_55
    -   Buero_68_C6_3A_87_FA_CE
    -   Wintergarten_40_91_51_4E_B4_5D
    -   Schlafzimmer_DC_4F_22_10_C6_0E
    -   Heizung_CC_50_E3_3B_F6_4D
    -   Heizung1_C2_8A_58_6E
    -   Jan_CC_50_E3_5D_A7_A5
    -   Lars_Zimmer_CC_50_E3_5D_A8_F3
    -   Lars_Dachboden_CC_50_E3_3C_06_71
    -   Keller_CC_50_E3_3C_13_D3
    -   Steckdose-Schuppen_EC_FA_BC_9B_CC_1D
    -   Treppe_84_F3_EB_B1_B0_A4
    -   Aquarium_EC_FA_BC_12_F6_8B
    -   Aquarium-2_CC_50_E3_53_1E_58
    -   Palisade_DC_4F_22_0A_F5_52
    -   Kugellampen_DC_4F_22_37_59_ED
    -   Schuppen_80_7D_3A_67_BD_24